INFRA: Initialize Acceptance Tests
Mums-Who-Code/ReserveSpot.Services pull request #10
Opened 2022-03-05 05:17 UTC by MahalakshmiMurari

2022-03-08 21:15 UTC, MahalakshmiMurari commented
Updated dotnet version to 7.0.100-preview.1.22110.4

2022-03-08 21:19 UTC, ShriHumrudha requested changes

2022-03-08 21:19 UTC, ShriHumrudha commented on ReserveSpot.Services.Infrastructure.Build/Program.cs
> +                                    DotNetVersion = "7.0.100-preview.1.22110.4",
Merge lastest so the code is already changed will be reflected.

2022-03-08 23:02 UTC, MahalakshmiMurari commented on ReserveSpot.Services.Infrastructure.Build/Program.cs
> +                                    DotNetVersion = "7.0.100-preview.1.22110.4",
Merged main branch into feature branch. Please review

2022-03-09 03:22 UTC, ShriHumrudha approved these changes

2022-03-09 19:05 UTC, merged