DATA: User Model and Migration
Mums-Who-Code/ReserveSpot.Services pull request #12
Opened 2022-03-17 02:09 UTC by MahalakshmiMurari

2022-03-26 04:17 UTC, MahalakshmiMurari commented
![image](https://user-images.githubusercontent.com/95454126/160224375-af8f67ba-daa8-49f2-bc5f-b919b35a25ff.png)

2022-03-26 05:19 UTC, NaynaMallick commented on ReserveSpot.Services.Api/Brokers/Storages/StorageBroker.User.Seeds.cs
> +
remove extra line

2022-03-26 05:20 UTC, NaynaMallick commented on ReserveSpot.Services.Api/Brokers/Storages/StorageBroker.cs
> +
remove extra line

2022-03-26 22:18 UTC, ShriHumrudha requested changes

2022-03-26 22:18 UTC, ShriHumrudha commented on ReserveSpot.Services.Api/Brokers/Storages/StorageBroker.User.Seeds.cs
> +                //Id = Guid.Parse("80aea9ae-967a-4718-b04e-97d2614b862b")
remove commented code

2022-03-26 23:42 UTC, MahalakshmiMurari commented on ReserveSpot.Services.Api/Brokers/Storages/StorageBroker.User.Seeds.cs
> +
Removed extra line

2022-03-26 23:45 UTC, MahalakshmiMurari commented on ReserveSpot.Services.Api/Brokers/Storages/StorageBroker.cs
> +
Removed extra line

2022-03-26 23:54 UTC, MahalakshmiMurari commented on ReserveSpot.Services.Api/Brokers/Storages/StorageBroker.User.Seeds.cs
> +                //Id = Guid.Parse("80aea9ae-967a-4718-b04e-97d2614b862b")
Removed commented code

2022-03-27 05:26 UTC, NaynaMallick commented on ReserveSpot.Services.Api/Brokers/Storages/StorageBroker.User.Seeds.cs
> +
remove extra line 22

2022-03-27 18:03 UTC, MahalakshmiMurari commented on ReserveSpot.Services.Api/Brokers/Storages/StorageBroker.User.Seeds.cs
> +
Removed extra line

2022-03-28 01:11 UTC, ShriHumrudha requested changes

2022-03-28 01:11 UTC, ShriHumrudha commented on ReserveSpot.Services.Api/Brokers/Storages/StorageBroker.cs
> +
I still see 23 and 24 as empty lines

2022-03-28 01:11 UTC, ShriHumrudha commented on ReserveSpot.Services.Api/ReserveSpot.Services.Api.csproj
> +		 <PackageReference Include="Microsoft.AspNetCore.OData" Version="8.0.8" />
Why do we need OData?

2022-03-28 15:56 UTC, MahalakshmiMurari commented on ReserveSpot.Services.Api/Brokers/Storages/StorageBroker.cs
> +
Removed extra line 24

2022-03-28 17:06 UTC, MahalakshmiMurari commented on ReserveSpot.Services.Api/ReserveSpot.Services.Api.csproj
> +		 <PackageReference Include="Microsoft.AspNetCore.OData" Version="8.0.8" />
This defines a composite OData query options that can be used to perform query composition. Right now, it is not required. By mistake it was copied from another file. So deleted that entry.

2022-03-29 01:13 UTC, ShriHumrudha requested changes

2022-03-29 01:13 UTC, ShriHumrudha commented on ReserveSpot.Services.Api/ReserveSpot.Services.Api.csproj
> +	    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.2" />
fix alignment

2022-03-29 04:59 UTC, MahalakshmiMurari commented on ReserveSpot.Services.Api/ReserveSpot.Services.Api.csproj
> +	    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.2" />
fixed alignment

2022-03-31 02:40 UTC, ShriHumrudha approved these changes

2022-04-04 15:44 UTC, merged