BROKER: Get Current Date Time
Mums-Who-Code/ReserveSpot.Services pull request #5
Opened 2022-02-11 02:20 UTC by MahalakshmiMurari

BROKER: Get Current Date Time
CODERUB: Infrastructure Build

2022-02-11 03:56 UTC, ShriHumrudha requested changes
Update your yml too

2022-02-11 05:04 UTC, MahalakshmiMurari commented
CODERUB: Ran Infrastructure build

2022-02-15 02:19 UTC, ShriHumrudha requested changes

2022-02-15 02:19 UTC, ShriHumrudha commented on ReserveSpot.Services.Api/Startup.cs
> +            services.AddSingleton<IDateTimeBroker, DateTimeBroker>();
Why Singleton?

2022-02-15 02:19 UTC, ShriHumrudha commented on ReserveSpot.Services.Api/Startup.cs
> +            services.AddSingleton<IDateTimeBroker, DateTimeBroker>();
Ping

2022-02-16 02:39 UTC, MahalakshmiMurari commented on ReserveSpot.Services.Api/Startup.cs
> +            services.AddSingleton<IDateTimeBroker, DateTimeBroker>();
Date and Time can be created and set for the first time and can be used further based on the request .
As Singleton lifetime services are created the first time they are requested and then every subsequent request will use .. so we used singleton.

2022-02-16 02:48 UTC, ShriHumrudha approved these changes

2022-02-16 02:48 UTC, ShriHumrudha commented on ReserveSpot.Services.Api/Startup.cs
> +            services.AddSingleton<IDateTimeBroker, DateTimeBroker>();
Stay careful with Singleton. If there is no real need to keep the state consistent then you can prefer Transient.

2022-02-17 02:15 UTC, MahalakshmiMurari commented on ReserveSpot.Services.Api/Startup.cs
> +            services.AddSingleton<IDateTimeBroker, DateTimeBroker>();
Changed the services to Transient. Please review and approve the PR

2022-02-17 02:57 UTC, ShriHumrudha approved these changes

2022-02-17 03:01 UTC, merged